// GENERATED by scripts/gen-prop-manifest.mjs — do not edit by hand.
// Prop model basenames discovered in client/public/models/props/.
export const PROP_MODELS: string[] = [
  "boulder",
  "bush",
  "cart",
  "flowers",
  "house",
  "lantern",
  "lumbermill",
  "market",
  "mill",
  "mushrooms",
  "pine_a",
  "pine_b",
  "town_tower",
  "town_wall",
  "watchtower",
  "well"
]
