// Canonical gather-task definitions shared by GatherScreen and the MCP idle engine.
// No UI imports; adding a task here makes it available to both.
export const GATHER_TASKS = [
  {
    id: 'gather_bowstring',
    name: 'Gather Bowstring',
    icon: '🌿',
    iconKey: 'thread',
    description: 'Gather loose bowstrings from fieldwork caches. Directly used for fletching bows.',
    ticks: 6,
    product: 'bowstring',
    qty: 1,
    stackable: false,
    category: 'fields',
  },
  {
    id: 'collect_sand',
    name: 'Collect Bucket of Sand',
    icon: '🏖️',
    iconKey: 'bucket',
    description: 'Collect sand from the beach. Used with seaweed to make glass.',
    ticks: 3,
    product: 'bucket_of_sand',
    qty: 1,
    stackable: false,
    category: 'beach',
  },
  {
    id: 'collect_seaweed',
    name: 'Collect Seaweed',
    icon: '🌊',
    iconKey: 'seaweed',
    description: 'Gather seaweed from the shore. Burnt with a bucket of sand to make glass.',
    ticks: 4,
    product: 'seaweed',
    qty: 1,
    stackable: false,
    category: 'beach',
  },
  {
    id: 'burn_seaweed',
    name: 'Burn Seaweed → Soda Ash',
    icon: '🔆',
    iconKey: 'flame',
    description: 'Burn seaweed to produce soda ash. Used with bucket of sand to make glass.',
    ticks: 3,
    product: 'soda_ash',
    qty: 1,
    stackable: false,
    materials: { seaweed: 1 },
    category: 'beach',
  },
  {
    id: 'catch_newts',
    name: 'Catch Eye of Newt',
    icon: '👁️',
    iconKey: 'eye',
    description: 'Catch newts from the pond and harvest their eyes. Used in many potions.',
    ticks: 4,
    product: 'eye_of_newt',
    qty: 1,
    stackable: true,
    category: 'fields',
  },
  {
    id: 'pick_white_berries',
    name: 'Pick White Berries',
    icon: '🫐',
    iconKey: 'berries',
    description: 'Pick white berries from the bushes. Used in defence and super restore potions.',
    ticks: 3,
    product: 'white_berries',
    qty: 1,
    stackable: true,
    category: 'fields',
  },
  {
    id: 'gather_snape_grass',
    name: 'Gather Snape Grass',
    icon: '🌾',
    iconKey: 'grass',
    description: 'Cut snape grass from the swamp. Used in prayer potions.',
    ticks: 3,
    product: 'snape_grass',
    qty: 1,
    stackable: true,
    category: 'fields',
  },
  {
    id: 'collect_spiders_eggs',
    name: 'Collect Red Spiders\' Eggs',
    icon: '🥚',
    iconKey: 'eggs',
    description: 'Collect eggs from red spiders. Used in super restore potions.',
    ticks: 4,
    product: 'red_spiders_eggs',
    qty: 1,
    stackable: true,
    category: 'fields',
  },
  {
    id: 'harvest_potato_cactus',
    name: 'Harvest Potato Cactus',
    icon: '🌵',
    iconKey: 'cactus',
    description: 'Harvest potato cactus from the desert. Used in magic and potion combinations.',
    ticks: 4,
    product: 'potato_cactus',
    qty: 1,
    stackable: true,
    category: 'beach',
  },
  {
    id: 'crush_birds_nest',
    name: 'Crush Birds Nest',
    icon: '🪹',
    iconKey: 'nest',
    description: 'Crush an empty bird\'s nest into a crushed bird\'s nest. Used in herblore brews.',
    ticks: 5,
    product: 'crushed_bird_s_nest',
    qty: 1,
    stackable: true,
    materials: { empty_bird_s_nest: 1 },
    category: 'fields',
  },
  {
    id: 'collect_wine_of_zamorak',
    name: 'Collect Wine of Krylth',
    icon: '🍷',
    iconKey: 'wine',
    description: 'Collect bottles of Wine of Krylth. Used in herblore to make ranging potions.',
    ticks: 5,
    product: 'wine_of_krylth',
    qty: 1,
    stackable: true,
    category: 'fields',
  },
  {
    id: 'pick_limpwurt_root',
    name: 'Pick Limpwurt Root',
    icon: '🌿',
    iconKey: 'herb',
    description: 'Harvest limpwurt roots from the swamp. Used in herblore to make super strength potions.',
    ticks: 3,
    product: 'limpwurt_root',
    qty: 1,
    stackable: true,
    category: 'fields',
  },
  {
    id: 'convert_log_to_plank',
    name: 'Convert Logs → Planks',
    icon: '🪵',
    iconKey: 'planks',
    description: 'Convert logs into planks at the sawmill. Costs 150gp per action.',
    ticks: 1,
    product: 'plank',
    qty: 1,
    stackable: true,
    materials: { logs: 1 },
    gpCost: 150,
    category: 'fields',
  },
  {
    id: 'convert_oak_log_to_plank',
    name: 'Convert Oak Logs → Oak Planks',
    icon: '🪵',
    iconKey: 'planks',
    description: 'Convert oak logs into oak planks at the sawmill. Costs 250gp per action.',
    ticks: 1,
    product: 'oak_plank',
    qty: 1,
    stackable: true,
    materials: { oak_logs: 1 },
    gpCost: 250,
    category: 'fields',
  },
  {
    id: 'convert_teak_log_to_plank',
    name: 'Convert Teak Logs → Teak Planks',
    icon: '🪵',
    iconKey: 'planks',
    description: 'Convert teak logs into teak planks at the sawmill. Costs 500gp per action.',
    ticks: 1,
    product: 'teak_plank',
    qty: 1,
    stackable: true,
    materials: { teak_logs: 1 },
    gpCost: 500,
    category: 'fields',
  },
  {
    id: 'convert_mahogany_log_to_plank',
    name: 'Convert Mahogany Logs → Mahogany Planks',
    icon: '🪵',
    iconKey: 'planks',
    description: 'Convert mahogany logs into mahogany planks at the sawmill. Costs 1500gp per action.',
    ticks: 1,
    product: 'mahogany_plank',
    qty: 1,
    stackable: true,
    materials: { mahogany_logs: 1 },
    gpCost: 1500,
    category: 'fields',
  },
]

export function findGatherTask(id) {
  return GATHER_TASKS.find((t) => t.id === id) || null
}
