// Per-monster emoji, extracted from CombatScreen so it can be shared with the
// open world's world map (R2-7, docs/open-world-changes-plan.md). No UI
// imports — safe in core (§12).
export const MONSTER_ICONS = {
  field_chicken: '🐔', cave_goblin: '👺', pasture_bull: '🐄', broodfang_spider: '🕷️',
  stoneback_crab: '🦀', duneback_crab: '🦀', highland_giant: '👊', briar_giant: '🌿', ember_giant: '🔥',
  elder_tree_spirit: '🌳', elder_rock_golem: '🗿',
  arcane_adept: '🧙', umbral_adept: '🧙‍♂️', hellbound_gorilla: '🦍',
  wailing_banshee: '👻', sanguine_veld: '🩸', warped_spectre: '👁️', ash_wyrm: '🐍',
  astral_warrior: '⚔️', astral_ranger: '🏹', astral_mage: '🔮', runestone_gargoyle: '🗿',
  bone_wyvern: '🐲', cinder_devil: '💨', deepmaw_kraken: '🦑', nightfang_beast: '🦇',
  marshscale_shaman: '🦎', nether_wraith: '👻', nether_demon: '😈', vicious_black_dragon: '🐉',
  threefang_cerberus: '🐺', ashen_hydra: '🐲',
  corporeal_horror: '👁️',
  zaryth_the_empty_lord: '🕳️',
  zaryth_blade_sentinel: '⚔️', zaryth_bolt_sentinel: '🏹', zaryth_rune_sentinel: '🔮',
  dustpaw_rat: '🐀', bogling_sprite: '✨', frostbite_imp: '❄️', marshfen_toad: '🐸',
  cinderpaw_cub: '🐅', glaive_skeleton: '💀', mirebound_husk: '🪦', verdant_stalker: '🏹',
  stoneglare_basilisk: '🦎', embertongue_lizard: '🦎', hollow_reaver: '⚰️',
  briarheart_treant: '🌳', frostmaw_direwolf: '🐺', pyreclaw_demon: '👹',
  wraithgale_specter: '👻', bloodmoon_stalker: '🌙', ironfang_drake: '🐲',
  shadeglass_golem: '🗿', tidereaper_crab: '🦀',
  voidweave_stalker: '🕸️', drakthul_wyrmling: '🐉', bonelight_pyromancer: '🔥',
  cinderfang_reaver: '🗡️', ashen_marauder: '⚒️', sovrathar_the_ashen_sovereign: '👑',
  green_dragon: '🐉', red_dragon: '🔴', adamant_dragon: '⚔️', rune_dragon: '🛡️', lesser_fiend: '👿',
  warlord_grondar: '👹', commander_zephyra: '🌟', krylth_the_defiler: '🔥', skyrender_kharra: '🦅',
  nagadoth_rex: '🦖', nagadoth_prime: '👹', nagadoth_supreme: '🏹', nagadoth_queen: '👑',
  nagadoth_rex_summon: '🦖', nagadoth_prime_summon: '👹', nagadoth_supreme_summon: '🏹',
  crazy_archaeologist: '📜', king_black_dragon: '👑', venomcoil_matriarch: '🐍', ember_tyrant: '🌋', ashen_crucible: '🌋', blighted_gauntlet: '⚡',
  tekton: '🔨', vespula: '🦟', muttadile: '🦷', the_great_olm: '🏛️',
  the_maiden_of_sugadinti: '🩸', pestilent_bloat: '🤢', nylocas_vasilias: '🕷️',
  sotetseg: '🔮', xarpus: '☠️', verzik_vitur: '👑',
  gravehusk_brute: '💀', boneclaw_revenant: '🦴', shroudwraith_specter: '👻',
  stonegale_elemental: '🪨', cindermaw_serpent: '🐍', thornhide_colossus: '🌳',
  ironclad_guardian: '⚙️', emberhowl_warlord: '🪓',
  gravethorn_drake: '🦎', razorwing_harpy: '🦅', duskmare: '🌑'
}
