export const PROP_BASE_SCALE = {
  pine_a: 1.7,
  pine_b: 1.6,
  bush: 1.4,
  mushrooms: 1.1,
  flowers: 1.1,
  boulder: 1.3,
  // Varrick capital landmarks (native model bounds → tile-grid units).
  castle: 3.0,
  fountain: 1.5,
  stall: 1.8,
  banner: 2.0,
  altar: 1.6,
  crypt: 2.2,
  column: 2.0,
  dungeon_stairs: 0.9,
  dungeon_door: 0.8,
  // Pasture and pit dressing (native model bounds → tile-grid units).
  fence: 1.0,
  fence_gate: 1.0,
  wheat: 1.4,
  hay_bale: 1.6,
  hay_stack: 1.8,
  torch: 1.6,
  stone_spire: 1.9,
  stone_spire_ember: 1.9,
  stone_slab: 1.4,
  skull: 0.32,
  bones: 1.2,
  obelisk: 2.6,
}
